repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-merge-conflict
        stages: [commit, push]
      - id: check-ast
        stages: [commit]
  - repo: https://github.com/doublify/pre-commit-rust
    rev: master
    hooks:
      - id: fmt
      - id: cargo-check